### ISSUE TITLE
i2c初始化报错-树莓派pico

### ISSUE THREAD

**Issue by jixishi** [jdhxyy/ssd1306py-micropython#1]
lcd.init_i2c(5, 4, 128, 64, 0)
TypeError: function takes 4 positional arguments but 5 were given

**Comment by jdhxyy** [comment]
def init_i2c(scl, sda, width, height):
    """
    初始化i2c接口
    :param scl: i2c的时钟脚
    :param sda: i2c的数据脚
    :param width: oled屏幕的宽度像素
    :param height: oled屏幕的高度像素
    """

多填写了一个参数。
